/*
 * generated by Xtext
 */
package com.alma.djynx.usecase;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UseCaseRuntimeModule extends com.alma.djynx.usecase.AbstractUseCaseRuntimeModule {

}
