/*
 * generated by Xtext
 */
package com.alma.djynx.usecase.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractUseCaseValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.alma.djynx.usecase.useCase.UseCasePackage.eINSTANCE);
		return result;
	}
}
