/**
 * generated by Xtext
 */
package com.alma.djynx.usecase.validation;

import com.alma.djynx.usecase.validation.AbstractUseCaseValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class UseCaseValidator extends AbstractUseCaseValidator {
}
