/*
 * generated by Xtext
 */
package com.alma.djynx.usecase.ui.contentassist

import com.alma.djynx.usecase.ui.contentassist.AbstractUseCaseProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class UseCaseProposalProvider extends AbstractUseCaseProposalProvider {
}
