/*
 * generated by Xtext
 */
package com.alma.djynx.usecase.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.alma.djynx.usecase.services.UseCaseGrammarAccess;

public class UseCaseParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UseCaseGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.alma.djynx.usecase.parser.antlr.internal.InternalUseCaseParser createParser(XtextTokenStream stream) {
		return new com.alma.djynx.usecase.parser.antlr.internal.InternalUseCaseParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "UseCase";
	}
	
	public UseCaseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UseCaseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
