/*
 * generated by Xtext
 */
package com.alma.djynx.usecase;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class UseCaseUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.alma.djynx.usecase.ui.internal.UseCaseActivator.getInstance().getInjector("com.alma.djynx.usecase.UseCase");
	}
	
}
