/*
 * generated by Xtext
 */
package com.alma.djynx.usecase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UseCaseUiModule extends com.alma.djynx.usecase.ui.AbstractUseCaseUiModule {
	public UseCaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
