/*
 * generated by Xtext
 */
package com.alma.djynx.usecase.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.alma.djynx.usecase.ui.internal.UseCaseActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UseCaseExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return UseCaseActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return UseCaseActivator.getInstance().getInjector(UseCaseActivator.COM_ALMA_DJYNX_USECASE_USECASE);
	}
	
}
